### ISSUE TITLE
why do you use Spring cloud stream

### ISSUE THREAD

**Issue by HelloTo4x** [ivangfr/spring-cloud-stream-kafka-elasticsearch#4]
Hi,i am reading your project, can i ask u a question, why do you choose Spring cloud stream, can u tell me your purpose and pros, cons of Spring cloud stream, when should we use Spring Cloud Stream, thank u so much

**Comment by ivangfr** [comment]
see comment on https://github.com/ivangfr/springboot-vault-examples/issues/2
